### ISSUE TITLE
Add requirements to README

### ISSUE THREAD

**Issue by quentin-cy** [awslabs/coldsnap#334]
As far as I could tell, it is required to have the `aws cli` installed and configured.
It is mentioned nowhere though.
Of course it might seem obvious to most users, but if you are an AWS newbie and quickly want to get something done on a new machine, well you are out of luck.

Also the error message is absolutely not helpful when `aws cli` is missing.

I happily make a PR for the README, if you confirm me that my assumptions about the requirements are correct :)

Thanks for the hard work
Q.

Edit (from webern):

- [ ] Update the README to make it more clear how credentials are obtained
- [ ] See if the error message can be improved (the underlying error seems to be missing)

**Comment by webern** [comment]
The `aws cli` is not, or at least should not be, required for the operation of `coldsnap`. However... it does require credentials and maybe it is through setting up the `aws cli` that you instantiated `~/.aws/config` and `~/aws/credentials` files which then provided the `coldsnap` CLI with credentials?

- Can you confirm that you were using the `coldsnap` CLI (and not the library)?
- Could you provide the error message that you saw that was not helpful? (Even if it wasn't user friendly, it might still tell us where the error was thrown in the code.)

I'm speculating here, but if you temporarily renamed `mv ~/.aws/ ~/.aws-hidden/`, do you get the error that you saw before?

Thanks.

**Comment by quentin-cy** [comment]
Hello @webern

Thank you for your answer ! You seem to be completely right, more specifically to answer your points:

- Yes I use `coldsnap` CLI, that I installed using the `cargo` as instructed in the README
- After moving the `.aws` as suggested I get the same error message again:
> Failed to download snapshot: Failed to list snapshot blocks 'snap-0123456789': dispatch failure

Thanks for looking into those beginner issues. I think they help making your tool more accessible :)

Cheers
Q

**Comment by webern** [comment]
Ok, thank you. I think there are two things that should be done to make this experience better. I will add these as checkboxes to your original message. Update the README to explain how credentials can be provided, and see if a better error message can be provided.

**Comment by jfbvm** [comment]
Another requirement that needs to be mentioned is the RAM!!! It really needs to have a minimum of 5GB of RAM.
I tried to install it in a virtual cloud machine with 2Gb, 3GB, and 4GB, and doesn't work (returned the error below), so when I updated the machine to 5GB, it worked...

Pls improve the readme file with this.

Compiling coldsnap v0.6.1
    Building [=======================> ] 184/186: aws-sdk-ec2
error: could not compile `aws-sdk-ec2` (lib)

Caused by:
  process didn't exit successfully: `/home/comba/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc --crate-name aws_sdk_ec2
--edition=2021 /home/comba/.cargo/registry/src/index.crates.io-6f17d22bba15001f/aws-sdk-ec2-1.23.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --diagnostic-width=135 --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="rt-tokio"' --cfg 'feature="rustls"' -C metadata=ac084b4c3f39bdbf -C extra-filename=-ac084b4c3f39bdbf --out-dir /tmp/cargo-installkXWaoC/release/deps -C strip=debuginfo -L dependency=/tmp/cargo-installkXWaoC/release/deps --extern aws_credential_types=/tmp/cargo-installkXWaoC/release/deps/libaws_credential_types-95c298380b1189af.rmeta --extern aws_runtime=/tmp/cargo-installkXWaoC/release/deps/libaws_runtime-508b96a2ca84b4cb.rmeta --extern aws_smithy_async=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_async-7b7b23922958e8f3.rmeta --extern aws_smithy_http=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_http-ec153dc17646ee2d.rmeta --extern aws_smithy_json=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_json-934e2124ec33ff4d.rmeta --extern aws_smithy_query=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_query-ed9e7731ef2f0f67.rmeta --extern aws_smithy_runtime=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_runtime-37fe1b81ff8cac6d.rmeta --extern aws_smithy_runtime_api=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_runtime_api-f335fa9196d8916e.rmeta --extern aws_smithy_types=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_types-e0c511d38b93c36e.rmeta --extern aws_smithy_xml=/tmp/cargo-installkXWaoC/release/deps/libaws_smithy_xml-ee6d6ecdbe3d76d1.rmeta --extern aws_types=/tmp/cargo-installkXWaoC/release/deps/libaws_types-4504b907d1386da1.rmeta --extern fastrand=/tmp/cargo-installkXWaoC/release/deps/libfastrand-52b7c130bcee7c7a.rmeta --extern http=/tmp/cargo-installkXWaoC/release/deps/libhttp-aa494bac7225e697.rmeta --extern once_cell=/tmp/cargo-installkXWaoC/release/deps/libonce_cell-09fe0f2ed9be70e2.rmeta --extern regex_lite=/tmp/cargo-installkXWaoC/release/deps/libregex_lite-27aa1cbc7784a7a3.rmeta --extern tracing=/tmp/cargo-installkXWaoC/release/deps/libtracing-08d10554205e5f39.rmeta --cap-lints allow -L native=/tmp/cargo-installkXWaoC/release/build/ring-3161d58ff3449950/out` (signal: 9, SIGKILL: kill)
error: failed to compile `coldsnap v0.6.1`, intermediate artifacts can be found at `/tmp/cargo-installkXWaoC`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
